# Generated by Django 3.0.6 on 2020-07-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200724_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imageLink',
            field=models.CharField(default='google.com', max_length=300),
            preserve_default=False,
        ),
    ]
